### ISSUE TITLE
dex parser not parsing all inner instruction

### ISSUE THREAD

**Issue by nuel77** [Topledger/solana-programs#26]
example tx: https://solana.fm/tx/xcWRaJbTWXDsYch6eC7E1V3Y38CoX3LJ5fMAGCapVvwjzcSukoNXPrSndCf9HwgfKeyABunN4P6m87JaFEhx1Hu?cluster=mainnet-alpha

Jupiter aggregator makes two swaps 
1) radium clmm swap
2) metoera dlmm 

When i use the substream to stream in the block only the radium clmm swap is parsed. The metora swap is missing.

attached output of the block here: https://gist.github.com/nuel77/111b05bf5a043c26cfbe2343cbc309b7

**Comment by harshvardhansharma** [comment]
Hey @nuel77, We tried running the dex-trades substream for the block number - `281251436` (block in which above mentioned tx is present) and are able to get the Swap instruction from Metoera DLMM(`LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo`) in output.

Output: https://gist.github.com/harshvardhansharma/07472046341d57fe38d769a693bcab38

<img width="1077" alt="Screenshot 2024-08-27 at 5 03 59 PM" src="https://github.com/user-attachments/assets/ae80c3bc-b548-4acf-aa14-de392acad883">


Can you check if you're using the latest version of dex-trades substream - `tl-solana-dex-trades-1-0-15-v1.0.15.spkg`

**Comment by nuel77** [comment]
ah, i took the most downloaded verision: https://substreams.dev/topledger/tl-solana-dex-trades-1-0-13/v1.0.13, it was not parsing here. Woring in the latest one.

**Comment by dkdocs** [comment]
I published `tl-solana-dex-trades-1-0-15-v1.0.15.spkg` earlier today too to Substreams.dev

**Comment by dkdocs** [comment]
Marking this as resolved!
